/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempGeneralDeclaration service. Represents a row in the &quot;TEMP_GENERAL_DECLARATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempGeneralDeclarationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempGeneralDeclarationImpl}.
 * </p>
 *
 * @author win_64
 * @see TempGeneralDeclaration
 * @see vn.gt.dao.noticeandmessage.model.impl.TempGeneralDeclarationImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempGeneralDeclarationModelImpl
 * @generated
 */
public interface TempGeneralDeclarationModel extends BaseModel<TempGeneralDeclaration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp general declaration model instance should use the {@link TempGeneralDeclaration} interface instead.
	 */

	/**
	 * Returns the primary key of this temp general declaration.
	 *
	 * @return the primary key of this temp general declaration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp general declaration.
	 *
	 * @param primaryKey the primary key of this temp general declaration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp general declaration.
	 *
	 * @return the ID of this temp general declaration
	 */
	public long getId();

	/**
	 * Sets the ID of this temp general declaration.
	 *
	 * @param id the ID of this temp general declaration
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp general declaration.
	 *
	 * @return the request code of this temp general declaration
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp general declaration.
	 *
	 * @param requestCode the request code of this temp general declaration
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the request state of this temp general declaration.
	 *
	 * @return the request state of this temp general declaration
	 */
	public int getRequestState();

	/**
	 * Sets the request state of this temp general declaration.
	 *
	 * @param requestState the request state of this temp general declaration
	 */
	public void setRequestState(int requestState);

	/**
	 * Returns the document name of this temp general declaration.
	 *
	 * @return the document name of this temp general declaration
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp general declaration.
	 *
	 * @param documentName the document name of this temp general declaration
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the document reference of this temp general declaration.
	 *
	 * @return the document reference of this temp general declaration
	 */
	public long getDocumentReference();

	/**
	 * Sets the document reference of this temp general declaration.
	 *
	 * @param documentReference the document reference of this temp general declaration
	 */
	public void setDocumentReference(long documentReference);

	/**
	 * Returns the document year of this temp general declaration.
	 *
	 * @return the document year of this temp general declaration
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp general declaration.
	 *
	 * @param documentYear the document year of this temp general declaration
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the user created of this temp general declaration.
	 *
	 * @return the user created of this temp general declaration
	 */
	@AutoEscape
	public String getUserCreated();

	/**
	 * Sets the user created of this temp general declaration.
	 *
	 * @param userCreated the user created of this temp general declaration
	 */
	public void setUserCreated(String userCreated);

	/**
	 * Returns the is arrival of this temp general declaration.
	 *
	 * @return the is arrival of this temp general declaration
	 */
	public int getIsArrival();

	/**
	 * Sets the is arrival of this temp general declaration.
	 *
	 * @param isArrival the is arrival of this temp general declaration
	 */
	public void setIsArrival(int isArrival);

	/**
	 * Returns the name of ship of this temp general declaration.
	 *
	 * @return the name of ship of this temp general declaration
	 */
	@AutoEscape
	public String getNameOfShip();

	/**
	 * Sets the name of ship of this temp general declaration.
	 *
	 * @param nameOfShip the name of ship of this temp general declaration
	 */
	public void setNameOfShip(String nameOfShip);

	/**
	 * Returns the ship type code of this temp general declaration.
	 *
	 * @return the ship type code of this temp general declaration
	 */
	@AutoEscape
	public String getShipTypeCode();

	/**
	 * Sets the ship type code of this temp general declaration.
	 *
	 * @param shipTypeCode the ship type code of this temp general declaration
	 */
	public void setShipTypeCode(String shipTypeCode);

	/**
	 * Returns the imo number of this temp general declaration.
	 *
	 * @return the imo number of this temp general declaration
	 */
	@AutoEscape
	public String getImoNumber();

	/**
	 * Sets the imo number of this temp general declaration.
	 *
	 * @param imoNumber the imo number of this temp general declaration
	 */
	public void setImoNumber(String imoNumber);

	/**
	 * Returns the call sign of this temp general declaration.
	 *
	 * @return the call sign of this temp general declaration
	 */
	@AutoEscape
	public String getCallSign();

	/**
	 * Sets the call sign of this temp general declaration.
	 *
	 * @param callSign the call sign of this temp general declaration
	 */
	public void setCallSign(String callSign);

	/**
	 * Returns the voyage number of this temp general declaration.
	 *
	 * @return the voyage number of this temp general declaration
	 */
	@AutoEscape
	public String getVoyageNumber();

	/**
	 * Sets the voyage number of this temp general declaration.
	 *
	 * @param voyageNumber the voyage number of this temp general declaration
	 */
	public void setVoyageNumber(String voyageNumber);

	/**
	 * Returns the port of arrival code of this temp general declaration.
	 *
	 * @return the port of arrival code of this temp general declaration
	 */
	@AutoEscape
	public String getPortOfArrivalCode();

	/**
	 * Sets the port of arrival code of this temp general declaration.
	 *
	 * @param portOfArrivalCode the port of arrival code of this temp general declaration
	 */
	public void setPortOfArrivalCode(String portOfArrivalCode);

	/**
	 * Returns the date of arrival of this temp general declaration.
	 *
	 * @return the date of arrival of this temp general declaration
	 */
	public Date getDateOfArrival();

	/**
	 * Sets the date of arrival of this temp general declaration.
	 *
	 * @param dateOfArrival the date of arrival of this temp general declaration
	 */
	public void setDateOfArrival(Date dateOfArrival);

	/**
	 * Returns the port harbour code of this temp general declaration.
	 *
	 * @return the port harbour code of this temp general declaration
	 */
	@AutoEscape
	public String getPortHarbourCode();

	/**
	 * Sets the port harbour code of this temp general declaration.
	 *
	 * @param portHarbourCode the port harbour code of this temp general declaration
	 */
	public void setPortHarbourCode(String portHarbourCode);

	/**
	 * Returns the port region code of this temp general declaration.
	 *
	 * @return the port region code of this temp general declaration
	 */
	@AutoEscape
	public String getPortRegionCode();

	/**
	 * Sets the port region code of this temp general declaration.
	 *
	 * @param portRegionCode the port region code of this temp general declaration
	 */
	public void setPortRegionCode(String portRegionCode);

	/**
	 * Returns the port wharf code of this temp general declaration.
	 *
	 * @return the port wharf code of this temp general declaration
	 */
	@AutoEscape
	public String getPortWharfCode();

	/**
	 * Sets the port wharf code of this temp general declaration.
	 *
	 * @param portWharfCode the port wharf code of this temp general declaration
	 */
	public void setPortWharfCode(String portWharfCode);

	/**
	 * Returns the flag state of ship of this temp general declaration.
	 *
	 * @return the flag state of ship of this temp general declaration
	 */
	@AutoEscape
	public String getFlagStateOfShip();

	/**
	 * Sets the flag state of ship of this temp general declaration.
	 *
	 * @param flagStateOfShip the flag state of ship of this temp general declaration
	 */
	public void setFlagStateOfShip(String flagStateOfShip);

	/**
	 * Returns the name of master of this temp general declaration.
	 *
	 * @return the name of master of this temp general declaration
	 */
	@AutoEscape
	public String getNameOfMaster();

	/**
	 * Sets the name of master of this temp general declaration.
	 *
	 * @param nameOfMaster the name of master of this temp general declaration
	 */
	public void setNameOfMaster(String nameOfMaster);

	/**
	 * Returns the last port of call code of this temp general declaration.
	 *
	 * @return the last port of call code of this temp general declaration
	 */
	@AutoEscape
	public String getLastPortOfCallCode();

	/**
	 * Sets the last port of call code of this temp general declaration.
	 *
	 * @param lastPortOfCallCode the last port of call code of this temp general declaration
	 */
	public void setLastPortOfCallCode(String lastPortOfCallCode);

	/**
	 * Returns the certificate of registry number of this temp general declaration.
	 *
	 * @return the certificate of registry number of this temp general declaration
	 */
	@AutoEscape
	public String getCertificateOfRegistryNumber();

	/**
	 * Sets the certificate of registry number of this temp general declaration.
	 *
	 * @param certificateOfRegistryNumber the certificate of registry number of this temp general declaration
	 */
	public void setCertificateOfRegistryNumber(
		String certificateOfRegistryNumber);

	/**
	 * Returns the certificate of registry date of this temp general declaration.
	 *
	 * @return the certificate of registry date of this temp general declaration
	 */
	public Date getCertificateOfRegistryDate();

	/**
	 * Sets the certificate of registry date of this temp general declaration.
	 *
	 * @param certificateOfRegistryDate the certificate of registry date of this temp general declaration
	 */
	public void setCertificateOfRegistryDate(Date certificateOfRegistryDate);

	/**
	 * Returns the certificate of registry port name of this temp general declaration.
	 *
	 * @return the certificate of registry port name of this temp general declaration
	 */
	@AutoEscape
	public String getCertificateOfRegistryPortName();

	/**
	 * Sets the certificate of registry port name of this temp general declaration.
	 *
	 * @param certificateOfRegistryPortName the certificate of registry port name of this temp general declaration
	 */
	public void setCertificateOfRegistryPortName(
		String certificateOfRegistryPortName);

	/**
	 * Returns the tax code of shipowners agents of this temp general declaration.
	 *
	 * @return the tax code of shipowners agents of this temp general declaration
	 */
	@AutoEscape
	public String getTaxCodeOfShipownersAgents();

	/**
	 * Sets the tax code of shipowners agents of this temp general declaration.
	 *
	 * @param taxCodeOfShipownersAgents the tax code of shipowners agents of this temp general declaration
	 */
	public void setTaxCodeOfShipownersAgents(String taxCodeOfShipownersAgents);

	/**
	 * Returns the name of shipowners agents of this temp general declaration.
	 *
	 * @return the name of shipowners agents of this temp general declaration
	 */
	@AutoEscape
	public String getNameOfShipownersAgents();

	/**
	 * Sets the name of shipowners agents of this temp general declaration.
	 *
	 * @param nameOfShipownersAgents the name of shipowners agents of this temp general declaration
	 */
	public void setNameOfShipownersAgents(String nameOfShipownersAgents);

	/**
	 * Returns the ship agency address of this temp general declaration.
	 *
	 * @return the ship agency address of this temp general declaration
	 */
	@AutoEscape
	public String getShipAgencyAddress();

	/**
	 * Sets the ship agency address of this temp general declaration.
	 *
	 * @param shipAgencyAddress the ship agency address of this temp general declaration
	 */
	public void setShipAgencyAddress(String shipAgencyAddress);

	/**
	 * Returns the ship agency phone of this temp general declaration.
	 *
	 * @return the ship agency phone of this temp general declaration
	 */
	@AutoEscape
	public String getShipAgencyPhone();

	/**
	 * Sets the ship agency phone of this temp general declaration.
	 *
	 * @param shipAgencyPhone the ship agency phone of this temp general declaration
	 */
	public void setShipAgencyPhone(String shipAgencyPhone);

	/**
	 * Returns the ship agency fax of this temp general declaration.
	 *
	 * @return the ship agency fax of this temp general declaration
	 */
	@AutoEscape
	public String getShipAgencyFax();

	/**
	 * Sets the ship agency fax of this temp general declaration.
	 *
	 * @param shipAgencyFax the ship agency fax of this temp general declaration
	 */
	public void setShipAgencyFax(String shipAgencyFax);

	/**
	 * Returns the ship agency email of this temp general declaration.
	 *
	 * @return the ship agency email of this temp general declaration
	 */
	@AutoEscape
	public String getShipAgencyEmail();

	/**
	 * Sets the ship agency email of this temp general declaration.
	 *
	 * @param shipAgencyEmail the ship agency email of this temp general declaration
	 */
	public void setShipAgencyEmail(String shipAgencyEmail);

	/**
	 * Returns the gross tonnage of this temp general declaration.
	 *
	 * @return the gross tonnage of this temp general declaration
	 */
	public double getGrossTonnage();

	/**
	 * Sets the gross tonnage of this temp general declaration.
	 *
	 * @param grossTonnage the gross tonnage of this temp general declaration
	 */
	public void setGrossTonnage(double grossTonnage);

	/**
	 * Returns the net tonnage of this temp general declaration.
	 *
	 * @return the net tonnage of this temp general declaration
	 */
	public double getNetTonnage();

	/**
	 * Sets the net tonnage of this temp general declaration.
	 *
	 * @param netTonnage the net tonnage of this temp general declaration
	 */
	public void setNetTonnage(double netTonnage);

	/**
	 * Returns the position of ship inport of this temp general declaration.
	 *
	 * @return the position of ship inport of this temp general declaration
	 */
	@AutoEscape
	public String getPositionOfShipInport();

	/**
	 * Sets the position of ship inport of this temp general declaration.
	 *
	 * @param positionOfShipInport the position of ship inport of this temp general declaration
	 */
	public void setPositionOfShipInport(String positionOfShipInport);

	/**
	 * Returns the brief particulars of voyage of this temp general declaration.
	 *
	 * @return the brief particulars of voyage of this temp general declaration
	 */
	@AutoEscape
	public String getBriefParticularsOfVoyage();

	/**
	 * Sets the brief particulars of voyage of this temp general declaration.
	 *
	 * @param briefParticularsOfVoyage the brief particulars of voyage of this temp general declaration
	 */
	public void setBriefParticularsOfVoyage(String briefParticularsOfVoyage);

	/**
	 * Returns the previous ports of call of this temp general declaration.
	 *
	 * @return the previous ports of call of this temp general declaration
	 */
	@AutoEscape
	public String getPreviousPortsOfCall();

	/**
	 * Sets the previous ports of call of this temp general declaration.
	 *
	 * @param previousPortsOfCall the previous ports of call of this temp general declaration
	 */
	public void setPreviousPortsOfCall(String previousPortsOfCall);

	/**
	 * Returns the subsequent ports of call of this temp general declaration.
	 *
	 * @return the subsequent ports of call of this temp general declaration
	 */
	@AutoEscape
	public String getSubsequentPortsOfCall();

	/**
	 * Sets the subsequent ports of call of this temp general declaration.
	 *
	 * @param subsequentPortsOfCall the subsequent ports of call of this temp general declaration
	 */
	public void setSubsequentPortsOfCall(String subsequentPortsOfCall);

	/**
	 * Returns the discharged ports of this temp general declaration.
	 *
	 * @return the discharged ports of this temp general declaration
	 */
	@AutoEscape
	public String getDischargedPorts();

	/**
	 * Sets the discharged ports of this temp general declaration.
	 *
	 * @param dischargedPorts the discharged ports of this temp general declaration
	 */
	public void setDischargedPorts(String dischargedPorts);

	/**
	 * Returns the remaining cargo of this temp general declaration.
	 *
	 * @return the remaining cargo of this temp general declaration
	 */
	@AutoEscape
	public String getRemainingCargo();

	/**
	 * Sets the remaining cargo of this temp general declaration.
	 *
	 * @param remainingCargo the remaining cargo of this temp general declaration
	 */
	public void setRemainingCargo(String remainingCargo);

	/**
	 * Returns the brief description of the cargo of this temp general declaration.
	 *
	 * @return the brief description of the cargo of this temp general declaration
	 */
	@AutoEscape
	public String getBriefDescriptionOfTheCargo();

	/**
	 * Sets the brief description of the cargo of this temp general declaration.
	 *
	 * @param briefDescriptionOfTheCargo the brief description of the cargo of this temp general declaration
	 */
	public void setBriefDescriptionOfTheCargo(String briefDescriptionOfTheCargo);

	/**
	 * Returns the number of crew of this temp general declaration.
	 *
	 * @return the number of crew of this temp general declaration
	 */
	public int getNumberOfCrew();

	/**
	 * Sets the number of crew of this temp general declaration.
	 *
	 * @param numberOfCrew the number of crew of this temp general declaration
	 */
	public void setNumberOfCrew(int numberOfCrew);

	/**
	 * Returns the number of passengers of this temp general declaration.
	 *
	 * @return the number of passengers of this temp general declaration
	 */
	public int getNumberOfPassengers();

	/**
	 * Sets the number of passengers of this temp general declaration.
	 *
	 * @param numberOfPassengers the number of passengers of this temp general declaration
	 */
	public void setNumberOfPassengers(int numberOfPassengers);

	/**
	 * Returns the ship requirements in terms of waste of this temp general declaration.
	 *
	 * @return the ship requirements in terms of waste of this temp general declaration
	 */
	@AutoEscape
	public String getShipRequirementsInTermsOfWaste();

	/**
	 * Sets the ship requirements in terms of waste of this temp general declaration.
	 *
	 * @param shipRequirementsInTermsOfWaste the ship requirements in terms of waste of this temp general declaration
	 */
	public void setShipRequirementsInTermsOfWaste(
		String shipRequirementsInTermsOfWaste);

	/**
	 * Returns the remarks of this temp general declaration.
	 *
	 * @return the remarks of this temp general declaration
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this temp general declaration.
	 *
	 * @param remarks the remarks of this temp general declaration
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the number cargo declaration of this temp general declaration.
	 *
	 * @return the number cargo declaration of this temp general declaration
	 */
	@AutoEscape
	public String getNumberCargoDeclaration();

	/**
	 * Sets the number cargo declaration of this temp general declaration.
	 *
	 * @param numberCargoDeclaration the number cargo declaration of this temp general declaration
	 */
	public void setNumberCargoDeclaration(String numberCargoDeclaration);

	/**
	 * Returns the number ship store declaration of this temp general declaration.
	 *
	 * @return the number ship store declaration of this temp general declaration
	 */
	@AutoEscape
	public String getNumberShipStoreDeclaration();

	/**
	 * Sets the number ship store declaration of this temp general declaration.
	 *
	 * @param numberShipStoreDeclaration the number ship store declaration of this temp general declaration
	 */
	public void setNumberShipStoreDeclaration(String numberShipStoreDeclaration);

	/**
	 * Returns the number crew list of this temp general declaration.
	 *
	 * @return the number crew list of this temp general declaration
	 */
	@AutoEscape
	public String getNumberCrewList();

	/**
	 * Sets the number crew list of this temp general declaration.
	 *
	 * @param numberCrewList the number crew list of this temp general declaration
	 */
	public void setNumberCrewList(String numberCrewList);

	/**
	 * Returns the number passenger list of this temp general declaration.
	 *
	 * @return the number passenger list of this temp general declaration
	 */
	@AutoEscape
	public String getNumberPassengerList();

	/**
	 * Sets the number passenger list of this temp general declaration.
	 *
	 * @param numberPassengerList the number passenger list of this temp general declaration
	 */
	public void setNumberPassengerList(String numberPassengerList);

	/**
	 * Returns the number crew effects of this temp general declaration.
	 *
	 * @return the number crew effects of this temp general declaration
	 */
	@AutoEscape
	public String getNumberCrewEffects();

	/**
	 * Sets the number crew effects of this temp general declaration.
	 *
	 * @param numberCrewEffects the number crew effects of this temp general declaration
	 */
	public void setNumberCrewEffects(String numberCrewEffects);

	/**
	 * Returns the number health maritime of this temp general declaration.
	 *
	 * @return the number health maritime of this temp general declaration
	 */
	@AutoEscape
	public String getNumberHealthMaritime();

	/**
	 * Sets the number health maritime of this temp general declaration.
	 *
	 * @param numberHealthMaritime the number health maritime of this temp general declaration
	 */
	public void setNumberHealthMaritime(String numberHealthMaritime);

	/**
	 * Returns the sign place of this temp general declaration.
	 *
	 * @return the sign place of this temp general declaration
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this temp general declaration.
	 *
	 * @param signPlace the sign place of this temp general declaration
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the sign date of this temp general declaration.
	 *
	 * @return the sign date of this temp general declaration
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this temp general declaration.
	 *
	 * @param signDate the sign date of this temp general declaration
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the master signed of this temp general declaration.
	 *
	 * @return the master signed of this temp general declaration
	 */
	public int getMasterSigned();

	/**
	 * Sets the master signed of this temp general declaration.
	 *
	 * @param masterSigned the master signed of this temp general declaration
	 */
	public void setMasterSigned(int masterSigned);

	/**
	 * Returns the master signed image of this temp general declaration.
	 *
	 * @return the master signed image of this temp general declaration
	 */
	public int getMasterSignedImage();

	/**
	 * Sets the master signed image of this temp general declaration.
	 *
	 * @param masterSignedImage the master signed image of this temp general declaration
	 */
	public void setMasterSignedImage(int masterSignedImage);

	/**
	 * Returns the cargo on board of this temp general declaration.
	 *
	 * @return the cargo on board of this temp general declaration
	 */
	@AutoEscape
	public String getCargoOnBoard();

	/**
	 * Sets the cargo on board of this temp general declaration.
	 *
	 * @param CargoOnBoard the cargo on board of this temp general declaration
	 */
	public void setCargoOnBoard(String CargoOnBoard);

	/**
	 * Returns the cargo of this temp general declaration.
	 *
	 * @return the cargo of this temp general declaration
	 */
	@AutoEscape
	public String getCargo();

	/**
	 * Sets the cargo of this temp general declaration.
	 *
	 * @param Cargo the cargo of this temp general declaration
	 */
	public void setCargo(String Cargo);

	/**
	 * Returns the volume cargo of this temp general declaration.
	 *
	 * @return the volume cargo of this temp general declaration
	 */
	public double getVolumeCargo();

	/**
	 * Sets the volume cargo of this temp general declaration.
	 *
	 * @param VolumeCargo the volume cargo of this temp general declaration
	 */
	public void setVolumeCargo(double VolumeCargo);

	/**
	 * Returns the cargo unit of this temp general declaration.
	 *
	 * @return the cargo unit of this temp general declaration
	 */
	@AutoEscape
	public String getCargoUnit();

	/**
	 * Sets the cargo unit of this temp general declaration.
	 *
	 * @param CargoUnit the cargo unit of this temp general declaration
	 */
	public void setCargoUnit(String CargoUnit);

	/**
	 * Returns the cargo description of this temp general declaration.
	 *
	 * @return the cargo description of this temp general declaration
	 */
	@AutoEscape
	public String getCargoDescription();

	/**
	 * Sets the cargo description of this temp general declaration.
	 *
	 * @param CargoDescription the cargo description of this temp general declaration
	 */
	public void setCargoDescription(String CargoDescription);

	/**
	 * Returns the rated power of this temp general declaration.
	 *
	 * @return the rated power of this temp general declaration
	 */
	@AutoEscape
	public String getRatedPower();

	/**
	 * Sets the rated power of this temp general declaration.
	 *
	 * @param ratedPower the rated power of this temp general declaration
	 */
	public void setRatedPower(String ratedPower);

	/**
	 * Returns the seating capacity of this temp general declaration.
	 *
	 * @return the seating capacity of this temp general declaration
	 */
	@AutoEscape
	public String getSeatingCapacity();

	/**
	 * Sets the seating capacity of this temp general declaration.
	 *
	 * @param seatingCapacity the seating capacity of this temp general declaration
	 */
	public void setSeatingCapacity(String seatingCapacity);

	/**
	 * Returns the lying capacity of this temp general declaration.
	 *
	 * @return the lying capacity of this temp general declaration
	 */
	@AutoEscape
	public String getLyingCapacity();

	/**
	 * Sets the lying capacity of this temp general declaration.
	 *
	 * @param lyingCapacity the lying capacity of this temp general declaration
	 */
	public void setLyingCapacity(String lyingCapacity);

	/**
	 * Returns the maritime port code of this temp general declaration.
	 *
	 * @return the maritime port code of this temp general declaration
	 */
	@AutoEscape
	public String getMaritimePortCode();

	/**
	 * Sets the maritime port code of this temp general declaration.
	 *
	 * @param maritimePortCode the maritime port code of this temp general declaration
	 */
	public void setMaritimePortCode(String maritimePortCode);

	/**
	 * Returns the last province code of this temp general declaration.
	 *
	 * @return the last province code of this temp general declaration
	 */
	@AutoEscape
	public String getLastProvinceCode();

	/**
	 * Sets the last province code of this temp general declaration.
	 *
	 * @param lastProvinceCode the last province code of this temp general declaration
	 */
	public void setLastProvinceCode(String lastProvinceCode);

	/**
	 * Returns the next province code of this temp general declaration.
	 *
	 * @return the next province code of this temp general declaration
	 */
	@AutoEscape
	public String getNextProvinceCode();

	/**
	 * Sets the next province code of this temp general declaration.
	 *
	 * @param nextProvinceCode the next province code of this temp general declaration
	 */
	public void setNextProvinceCode(String nextProvinceCode);

	/**
	 * Returns the last maritime port code of this temp general declaration.
	 *
	 * @return the last maritime port code of this temp general declaration
	 */
	@AutoEscape
	public String getLastMaritimePortCode();

	/**
	 * Sets the last maritime port code of this temp general declaration.
	 *
	 * @param lastMaritimePortCode the last maritime port code of this temp general declaration
	 */
	public void setLastMaritimePortCode(String lastMaritimePortCode);

	/**
	 * Returns the last port region code of this temp general declaration.
	 *
	 * @return the last port region code of this temp general declaration
	 */
	@AutoEscape
	public String getLastPortRegionCode();

	/**
	 * Sets the last port region code of this temp general declaration.
	 *
	 * @param lastPortRegionCode the last port region code of this temp general declaration
	 */
	public void setLastPortRegionCode(String lastPortRegionCode);

	/**
	 * Returns the last port harbour code of this temp general declaration.
	 *
	 * @return the last port harbour code of this temp general declaration
	 */
	@AutoEscape
	public String getLastPortHarbourCode();

	/**
	 * Sets the last port harbour code of this temp general declaration.
	 *
	 * @param lastPortHarbourCode the last port harbour code of this temp general declaration
	 */
	public void setLastPortHarbourCode(String lastPortHarbourCode);

	/**
	 * Returns the last port wharf code of this temp general declaration.
	 *
	 * @return the last port wharf code of this temp general declaration
	 */
	@AutoEscape
	public String getLastPortWharfCode();

	/**
	 * Sets the last port wharf code of this temp general declaration.
	 *
	 * @param lastPortWharfCode the last port wharf code of this temp general declaration
	 */
	public void setLastPortWharfCode(String lastPortWharfCode);

	/**
	 * Returns the next maritime port code of this temp general declaration.
	 *
	 * @return the next maritime port code of this temp general declaration
	 */
	@AutoEscape
	public String getNextMaritimePortCode();

	/**
	 * Sets the next maritime port code of this temp general declaration.
	 *
	 * @param nextMaritimePortCode the next maritime port code of this temp general declaration
	 */
	public void setNextMaritimePortCode(String nextMaritimePortCode);

	/**
	 * Returns the next port region code of this temp general declaration.
	 *
	 * @return the next port region code of this temp general declaration
	 */
	@AutoEscape
	public String getNextPortRegionCode();

	/**
	 * Sets the next port region code of this temp general declaration.
	 *
	 * @param nextPortRegionCode the next port region code of this temp general declaration
	 */
	public void setNextPortRegionCode(String nextPortRegionCode);

	/**
	 * Returns the next port harbour code of this temp general declaration.
	 *
	 * @return the next port harbour code of this temp general declaration
	 */
	@AutoEscape
	public String getNextPortHarbourCode();

	/**
	 * Sets the next port harbour code of this temp general declaration.
	 *
	 * @param nextPortHarbourCode the next port harbour code of this temp general declaration
	 */
	public void setNextPortHarbourCode(String nextPortHarbourCode);

	/**
	 * Returns the next port wharf code of this temp general declaration.
	 *
	 * @return the next port wharf code of this temp general declaration
	 */
	@AutoEscape
	public String getNextPortWharfCode();

	/**
	 * Sets the next port wharf code of this temp general declaration.
	 *
	 * @param nextPortWharfCode the next port wharf code of this temp general declaration
	 */
	public void setNextPortWharfCode(String nextPortWharfCode);

	/**
	 * Returns the link of this temp general declaration.
	 *
	 * @return the link of this temp general declaration
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this temp general declaration.
	 *
	 * @param link the link of this temp general declaration
	 */
	public void setLink(String link);

	/**
	 * Returns the qr code of this temp general declaration.
	 *
	 * @return the qr code of this temp general declaration
	 */
	@AutoEscape
	public String getQrCode();

	/**
	 * Sets the qr code of this temp general declaration.
	 *
	 * @param qrCode the qr code of this temp general declaration
	 */
	public void setQrCode(String qrCode);

	/**
	 * Returns the port clearance no of this temp general declaration.
	 *
	 * @return the port clearance no of this temp general declaration
	 */
	@AutoEscape
	public String getPortClearanceNo();

	/**
	 * Sets the port clearance no of this temp general declaration.
	 *
	 * @param portClearanceNo the port clearance no of this temp general declaration
	 */
	public void setPortClearanceNo(String portClearanceNo);

	/**
	 * Returns the loa of this temp general declaration.
	 *
	 * @return the loa of this temp general declaration
	 */
	public double getLoa();

	/**
	 * Sets the loa of this temp general declaration.
	 *
	 * @param loa the loa of this temp general declaration
	 */
	public void setLoa(double loa);

	/**
	 * Returns the unit l o a of this temp general declaration.
	 *
	 * @return the unit l o a of this temp general declaration
	 */
	@AutoEscape
	public String getUnitLOA();

	/**
	 * Sets the unit l o a of this temp general declaration.
	 *
	 * @param unitLOA the unit l o a of this temp general declaration
	 */
	public void setUnitLOA(String unitLOA);

	/**
	 * Returns the breadth of this temp general declaration.
	 *
	 * @return the breadth of this temp general declaration
	 */
	public double getBreadth();

	/**
	 * Sets the breadth of this temp general declaration.
	 *
	 * @param breadth the breadth of this temp general declaration
	 */
	public void setBreadth(double breadth);

	/**
	 * Returns the unit breadth of this temp general declaration.
	 *
	 * @return the unit breadth of this temp general declaration
	 */
	@AutoEscape
	public String getUnitBreadth();

	/**
	 * Sets the unit breadth of this temp general declaration.
	 *
	 * @param unitBreadth the unit breadth of this temp general declaration
	 */
	public void setUnitBreadth(String unitBreadth);

	/**
	 * Returns the clearance height of this temp general declaration.
	 *
	 * @return the clearance height of this temp general declaration
	 */
	public double getClearanceHeight();

	/**
	 * Sets the clearance height of this temp general declaration.
	 *
	 * @param clearanceHeight the clearance height of this temp general declaration
	 */
	public void setClearanceHeight(double clearanceHeight);

	/**
	 * Returns the unit clearance height of this temp general declaration.
	 *
	 * @return the unit clearance height of this temp general declaration
	 */
	@AutoEscape
	public String getUnitClearanceHeight();

	/**
	 * Sets the unit clearance height of this temp general declaration.
	 *
	 * @param unitClearanceHeight the unit clearance height of this temp general declaration
	 */
	public void setUnitClearanceHeight(String unitClearanceHeight);

	/**
	 * Returns the shown draftx f of this temp general declaration.
	 *
	 * @return the shown draftx f of this temp general declaration
	 */
	public double getShownDraftxF();

	/**
	 * Sets the shown draftx f of this temp general declaration.
	 *
	 * @param shownDraftxF the shown draftx f of this temp general declaration
	 */
	public void setShownDraftxF(double shownDraftxF);

	/**
	 * Returns the unit shown draftx f of this temp general declaration.
	 *
	 * @return the unit shown draftx f of this temp general declaration
	 */
	@AutoEscape
	public String getUnitShownDraftxF();

	/**
	 * Sets the unit shown draftx f of this temp general declaration.
	 *
	 * @param unitShownDraftxF the unit shown draftx f of this temp general declaration
	 */
	public void setUnitShownDraftxF(String unitShownDraftxF);

	/**
	 * Returns the shown draftx a of this temp general declaration.
	 *
	 * @return the shown draftx a of this temp general declaration
	 */
	public double getShownDraftxA();

	/**
	 * Sets the shown draftx a of this temp general declaration.
	 *
	 * @param shownDraftxA the shown draftx a of this temp general declaration
	 */
	public void setShownDraftxA(double shownDraftxA);

	/**
	 * Returns the unit shown draftx a of this temp general declaration.
	 *
	 * @return the unit shown draftx a of this temp general declaration
	 */
	@AutoEscape
	public String getUnitShownDraftxA();

	/**
	 * Sets the unit shown draftx a of this temp general declaration.
	 *
	 * @param unitShownDraftxA the unit shown draftx a of this temp general declaration
	 */
	public void setUnitShownDraftxA(String unitShownDraftxA);

	/**
	 * Returns the dwt of this temp general declaration.
	 *
	 * @return the dwt of this temp general declaration
	 */
	public double getDwt();

	/**
	 * Sets the dwt of this temp general declaration.
	 *
	 * @param dwt the dwt of this temp general declaration
	 */
	public void setDwt(double dwt);

	/**
	 * Returns the unit d w t of this temp general declaration.
	 *
	 * @return the unit d w t of this temp general declaration
	 */
	@AutoEscape
	public String getUnitDWT();

	/**
	 * Sets the unit d w t of this temp general declaration.
	 *
	 * @param unitDWT the unit d w t of this temp general declaration
	 */
	public void setUnitDWT(String unitDWT);

	/**
	 * Returns the time of p o r t arrival of this temp general declaration.
	 *
	 * @return the time of p o r t arrival of this temp general declaration
	 */
	public Date getTimeOfPORTArrival();

	/**
	 * Sets the time of p o r t arrival of this temp general declaration.
	 *
	 * @param timeOfPORTArrival the time of p o r t arrival of this temp general declaration
	 */
	public void setTimeOfPORTArrival(Date timeOfPORTArrival);

	/**
	 * Returns the time of pilot on board of this temp general declaration.
	 *
	 * @return the time of pilot on board of this temp general declaration
	 */
	public Date getTimeOfPilotOnBoard();

	/**
	 * Sets the time of pilot on board of this temp general declaration.
	 *
	 * @param timeOfPilotOnBoard the time of pilot on board of this temp general declaration
	 */
	public void setTimeOfPilotOnBoard(Date timeOfPilotOnBoard);

	/**
	 * Returns the tug boat of this temp general declaration.
	 *
	 * @return the tug boat of this temp general declaration
	 */
	@AutoEscape
	public String getTugBoat();

	/**
	 * Sets the tug boat of this temp general declaration.
	 *
	 * @param tugBoat the tug boat of this temp general declaration
	 */
	public void setTugBoat(String tugBoat);

	/**
	 * Returns the do_ of this temp general declaration.
	 *
	 * @return the do_ of this temp general declaration
	 */
	@AutoEscape
	public String getDo_();

	/**
	 * Sets the do_ of this temp general declaration.
	 *
	 * @param do_ the do_ of this temp general declaration
	 */
	public void setDo_(String do_);

	/**
	 * Returns the fo of this temp general declaration.
	 *
	 * @return the fo of this temp general declaration
	 */
	@AutoEscape
	public String getFo();

	/**
	 * Sets the fo of this temp general declaration.
	 *
	 * @param fo the fo of this temp general declaration
	 */
	public void setFo(String fo);

	/**
	 * Returns the fw of this temp general declaration.
	 *
	 * @return the fw of this temp general declaration
	 */
	@AutoEscape
	public String getFw();

	/**
	 * Sets the fw of this temp general declaration.
	 *
	 * @param fw the fw of this temp general declaration
	 */
	public void setFw(String fw);

	/**
	 * Returns the place of reception of this temp general declaration.
	 *
	 * @return the place of reception of this temp general declaration
	 */
	@AutoEscape
	public String getPlaceOfReception();

	/**
	 * Sets the place of reception of this temp general declaration.
	 *
	 * @param placeOfReception the place of reception of this temp general declaration
	 */
	public void setPlaceOfReception(String placeOfReception);

	/**
	 * Returns the name of ship owners of this temp general declaration.
	 *
	 * @return the name of ship owners of this temp general declaration
	 */
	@AutoEscape
	public String getNameOfShipOwners();

	/**
	 * Sets the name of ship owners of this temp general declaration.
	 *
	 * @param nameOfShipOwners the name of ship owners of this temp general declaration
	 */
	public void setNameOfShipOwners(String nameOfShipOwners);

	/**
	 * Returns the address of ship owners of this temp general declaration.
	 *
	 * @return the address of ship owners of this temp general declaration
	 */
	@AutoEscape
	public String getAddressOfShipOwners();

	/**
	 * Sets the address of ship owners of this temp general declaration.
	 *
	 * @param addressOfShipOwners the address of ship owners of this temp general declaration
	 */
	public void setAddressOfShipOwners(String addressOfShipOwners);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempGeneralDeclaration tempGeneralDeclaration);

	public int hashCode();

	public CacheModel<TempGeneralDeclaration> toCacheModel();

	public TempGeneralDeclaration toEscapedModel();

	public String toString();

	public String toXmlString();
}