/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmuc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmDataItem service. Represents a row in the &quot;dm_dataitem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmuc.model.impl.DmDataItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmuc.model.impl.DmDataItemImpl}.
 * </p>
 *
 * @author win_64
 * @see DmDataItem
 * @see vn.gt.dao.danhmuc.model.impl.DmDataItemImpl
 * @see vn.gt.dao.danhmuc.model.impl.DmDataItemModelImpl
 * @generated
 */
public interface DmDataItemModel extends BaseModel<DmDataItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm data item model instance should use the {@link DmDataItem} interface instead.
	 */

	/**
	 * Returns the primary key of this dm data item.
	 *
	 * @return the primary key of this dm data item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dm data item.
	 *
	 * @param primaryKey the primary key of this dm data item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dm data item.
	 *
	 * @return the ID of this dm data item
	 */
	public long getId();

	/**
	 * Sets the ID of this dm data item.
	 *
	 * @param Id the ID of this dm data item
	 */
	public void setId(long Id);

	/**
	 * Returns the data group ID of this dm data item.
	 *
	 * @return the data group ID of this dm data item
	 */
	public long getDataGroupId();

	/**
	 * Sets the data group ID of this dm data item.
	 *
	 * @param DataGroupId the data group ID of this dm data item
	 */
	public void setDataGroupId(long DataGroupId);

	/**
	 * Returns the code0 of this dm data item.
	 *
	 * @return the code0 of this dm data item
	 */
	@AutoEscape
	public String getCode0();

	/**
	 * Sets the code0 of this dm data item.
	 *
	 * @param Code0 the code0 of this dm data item
	 */
	public void setCode0(String Code0);

	/**
	 * Returns the node1 of this dm data item.
	 *
	 * @return the node1 of this dm data item
	 */
	@AutoEscape
	public String getNode1();

	/**
	 * Sets the node1 of this dm data item.
	 *
	 * @param Node1 the node1 of this dm data item
	 */
	public void setNode1(String Node1);

	/**
	 * Returns the node2 of this dm data item.
	 *
	 * @return the node2 of this dm data item
	 */
	@AutoEscape
	public String getNode2();

	/**
	 * Sets the node2 of this dm data item.
	 *
	 * @param Node2 the node2 of this dm data item
	 */
	public void setNode2(String Node2);

	/**
	 * Returns the node3 of this dm data item.
	 *
	 * @return the node3 of this dm data item
	 */
	@AutoEscape
	public String getNode3();

	/**
	 * Sets the node3 of this dm data item.
	 *
	 * @param Node3 the node3 of this dm data item
	 */
	public void setNode3(String Node3);

	/**
	 * Returns the node4 of this dm data item.
	 *
	 * @return the node4 of this dm data item
	 */
	@AutoEscape
	public String getNode4();

	/**
	 * Sets the node4 of this dm data item.
	 *
	 * @param Node4 the node4 of this dm data item
	 */
	public void setNode4(String Node4);

	/**
	 * Returns the level of this dm data item.
	 *
	 * @return the level of this dm data item
	 */
	public int getLevel();

	/**
	 * Sets the level of this dm data item.
	 *
	 * @param Level the level of this dm data item
	 */
	public void setLevel(int Level);

	/**
	 * Returns the name of this dm data item.
	 *
	 * @return the name of this dm data item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dm data item.
	 *
	 * @param Name the name of this dm data item
	 */
	public void setName(String Name);

	/**
	 * Returns the short name of this dm data item.
	 *
	 * @return the short name of this dm data item
	 */
	@AutoEscape
	public String getShortName();

	/**
	 * Sets the short name of this dm data item.
	 *
	 * @param ShortName the short name of this dm data item
	 */
	public void setShortName(String ShortName);

	/**
	 * Returns the description of this dm data item.
	 *
	 * @return the description of this dm data item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this dm data item.
	 *
	 * @param Description the description of this dm data item
	 */
	public void setDescription(String Description);

	/**
	 * Returns the validated from of this dm data item.
	 *
	 * @return the validated from of this dm data item
	 */
	public Date getValidatedFrom();

	/**
	 * Sets the validated from of this dm data item.
	 *
	 * @param ValidatedFrom the validated from of this dm data item
	 */
	public void setValidatedFrom(Date ValidatedFrom);

	/**
	 * Returns the validated to of this dm data item.
	 *
	 * @return the validated to of this dm data item
	 */
	public Date getValidatedTo();

	/**
	 * Sets the validated to of this dm data item.
	 *
	 * @param ValidatedTo the validated to of this dm data item
	 */
	public void setValidatedTo(Date ValidatedTo);

	/**
	 * Returns the order of this dm data item.
	 *
	 * @return the order of this dm data item
	 */
	public int getOrder();

	/**
	 * Sets the order of this dm data item.
	 *
	 * @param Order the order of this dm data item
	 */
	public void setOrder(int Order);

	/**
	 * Returns the status of this dm data item.
	 *
	 * @return the status of this dm data item
	 */
	public int getStatus();

	/**
	 * Sets the status of this dm data item.
	 *
	 * @param Status the status of this dm data item
	 */
	public void setStatus(int Status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmDataItem dmDataItem);

	public int hashCode();

	public CacheModel<DmDataItem> toCacheModel();

	public DmDataItem toEscapedModel();

	public String toString();

	public String toXmlString();
}