/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TempWasteList service. Represents a row in the &quot;TEMP_WASTE_LIST&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempWasteListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempWasteListImpl}.
 * </p>
 *
 * @author win_64
 * @see TempWasteList
 * @see vn.gt.dao.noticeandmessage.model.impl.TempWasteListImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempWasteListModelImpl
 * @generated
 */
public interface TempWasteListModel extends BaseModel<TempWasteList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp waste list model instance should use the {@link TempWasteList} interface instead.
	 */

	/**
	 * Returns the primary key of this temp waste list.
	 *
	 * @return the primary key of this temp waste list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp waste list.
	 *
	 * @param primaryKey the primary key of this temp waste list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp waste list.
	 *
	 * @return the ID of this temp waste list
	 */
	public long getId();

	/**
	 * Sets the ID of this temp waste list.
	 *
	 * @param id the ID of this temp waste list
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp waste list.
	 *
	 * @return the request code of this temp waste list
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp waste list.
	 *
	 * @param requestCode the request code of this temp waste list
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the document name of this temp waste list.
	 *
	 * @return the document name of this temp waste list
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp waste list.
	 *
	 * @param documentName the document name of this temp waste list
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the document year of this temp waste list.
	 *
	 * @return the document year of this temp waste list
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp waste list.
	 *
	 * @param documentYear the document year of this temp waste list
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the type code of this temp waste list.
	 *
	 * @return the type code of this temp waste list
	 */
	@AutoEscape
	public String getTypeCode();

	/**
	 * Sets the type code of this temp waste list.
	 *
	 * @param typeCode the type code of this temp waste list
	 */
	public void setTypeCode(String typeCode);

	/**
	 * Returns the type name of this temp waste list.
	 *
	 * @return the type name of this temp waste list
	 */
	@AutoEscape
	public String getTypeName();

	/**
	 * Sets the type name of this temp waste list.
	 *
	 * @param typeName the type name of this temp waste list
	 */
	public void setTypeName(String typeName);

	/**
	 * Returns the weight of this temp waste list.
	 *
	 * @return the weight of this temp waste list
	 */
	public double getWeight();

	/**
	 * Sets the weight of this temp waste list.
	 *
	 * @param weight the weight of this temp waste list
	 */
	public void setWeight(double weight);

	/**
	 * Returns the unit of this temp waste list.
	 *
	 * @return the unit of this temp waste list
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this temp waste list.
	 *
	 * @param unit the unit of this temp waste list
	 */
	public void setUnit(String unit);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempWasteList tempWasteList);

	public int hashCode();

	public CacheModel<TempWasteList> toCacheModel();

	public TempWasteList toEscapedModel();

	public String toString();

	public String toXmlString();
}