/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TempPersonList service. Represents a row in the &quot;TEMP_PERSON_LIST&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempPersonListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempPersonListImpl}.
 * </p>
 *
 * @author win_64
 * @see TempPersonList
 * @see vn.gt.dao.noticeandmessage.model.impl.TempPersonListImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempPersonListModelImpl
 * @generated
 */
public interface TempPersonListModel extends BaseModel<TempPersonList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp person list model instance should use the {@link TempPersonList} interface instead.
	 */

	/**
	 * Returns the primary key of this temp person list.
	 *
	 * @return the primary key of this temp person list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp person list.
	 *
	 * @param primaryKey the primary key of this temp person list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp person list.
	 *
	 * @return the ID of this temp person list
	 */
	public long getId();

	/**
	 * Sets the ID of this temp person list.
	 *
	 * @param id the ID of this temp person list
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp person list.
	 *
	 * @return the request code of this temp person list
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp person list.
	 *
	 * @param requestCode the request code of this temp person list
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the document name of this temp person list.
	 *
	 * @return the document name of this temp person list
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp person list.
	 *
	 * @param documentName the document name of this temp person list
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the document year of this temp person list.
	 *
	 * @return the document year of this temp person list
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp person list.
	 *
	 * @param documentYear the document year of this temp person list
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the name of this temp person list.
	 *
	 * @return the name of this temp person list
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this temp person list.
	 *
	 * @param name the name of this temp person list
	 */
	public void setName(String name);

	/**
	 * Returns the age of this temp person list.
	 *
	 * @return the age of this temp person list
	 */
	@AutoEscape
	public String getAge();

	/**
	 * Sets the age of this temp person list.
	 *
	 * @param age the age of this temp person list
	 */
	public void setAge(String age);

	/**
	 * Returns the national code of this temp person list.
	 *
	 * @return the national code of this temp person list
	 */
	@AutoEscape
	public String getNationalCode();

	/**
	 * Sets the national code of this temp person list.
	 *
	 * @param nationalCode the national code of this temp person list
	 */
	public void setNationalCode(String nationalCode);

	/**
	 * Returns the national name of this temp person list.
	 *
	 * @return the national name of this temp person list
	 */
	@AutoEscape
	public String getNationalName();

	/**
	 * Sets the national name of this temp person list.
	 *
	 * @param nationalName the national name of this temp person list
	 */
	public void setNationalName(String nationalName);

	/**
	 * Returns the ilness status of this temp person list.
	 *
	 * @return the ilness status of this temp person list
	 */
	@AutoEscape
	public String getIlnessStatus();

	/**
	 * Sets the ilness status of this temp person list.
	 *
	 * @param ilnessStatus the ilness status of this temp person list
	 */
	public void setIlnessStatus(String ilnessStatus);

	/**
	 * Returns the reason of dead of this temp person list.
	 *
	 * @return the reason of dead of this temp person list
	 */
	@AutoEscape
	public String getReasonOfDead();

	/**
	 * Sets the reason of dead of this temp person list.
	 *
	 * @param reasonOfDead the reason of dead of this temp person list
	 */
	public void setReasonOfDead(String reasonOfDead);

	/**
	 * Returns the person type of this temp person list.
	 *
	 * @return the person type of this temp person list
	 */
	public int getPersonType();

	/**
	 * Sets the person type of this temp person list.
	 *
	 * @param personType the person type of this temp person list
	 */
	public void setPersonType(int personType);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempPersonList tempPersonList);

	public int hashCode();

	public CacheModel<TempPersonList> toCacheModel();

	public TempPersonList toEscapedModel();

	public String toString();

	public String toXmlString();
}