/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempCargoItems service. Represents a row in the &quot;TEMP_CARGO_ITEMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempCargoItemsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempCargoItemsImpl}.
 * </p>
 *
 * @author win_64
 * @see TempCargoItems
 * @see vn.gt.dao.noticeandmessage.model.impl.TempCargoItemsImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempCargoItemsModelImpl
 * @generated
 */
public interface TempCargoItemsModel extends BaseModel<TempCargoItems> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp cargo items model instance should use the {@link TempCargoItems} interface instead.
	 */

	/**
	 * Returns the primary key of this temp cargo items.
	 *
	 * @return the primary key of this temp cargo items
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp cargo items.
	 *
	 * @param primaryKey the primary key of this temp cargo items
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp cargo items.
	 *
	 * @return the ID of this temp cargo items
	 */
	public long getId();

	/**
	 * Sets the ID of this temp cargo items.
	 *
	 * @param id the ID of this temp cargo items
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp cargo items.
	 *
	 * @return the request code of this temp cargo items
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp cargo items.
	 *
	 * @param requestCode the request code of this temp cargo items
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the document name of this temp cargo items.
	 *
	 * @return the document name of this temp cargo items
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp cargo items.
	 *
	 * @param documentName the document name of this temp cargo items
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the document year of this temp cargo items.
	 *
	 * @return the document year of this temp cargo items
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp cargo items.
	 *
	 * @param documentYear the document year of this temp cargo items
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the cargo category of this temp cargo items.
	 *
	 * @return the cargo category of this temp cargo items
	 */
	@AutoEscape
	public String getCargoCategory();

	/**
	 * Sets the cargo category of this temp cargo items.
	 *
	 * @param cargoCategory the cargo category of this temp cargo items
	 */
	public void setCargoCategory(String cargoCategory);

	/**
	 * Returns the cargo type of this temp cargo items.
	 *
	 * @return the cargo type of this temp cargo items
	 */
	@AutoEscape
	public String getCargoType();

	/**
	 * Sets the cargo type of this temp cargo items.
	 *
	 * @param cargoType the cargo type of this temp cargo items
	 */
	public void setCargoType(String cargoType);

	/**
	 * Returns the cargo code of this temp cargo items.
	 *
	 * @return the cargo code of this temp cargo items
	 */
	@AutoEscape
	public String getCargoCode();

	/**
	 * Sets the cargo code of this temp cargo items.
	 *
	 * @param cargoCode the cargo code of this temp cargo items
	 */
	public void setCargoCode(String cargoCode);

	/**
	 * Returns the description of this temp cargo items.
	 *
	 * @return the description of this temp cargo items
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this temp cargo items.
	 *
	 * @param description the description of this temp cargo items
	 */
	public void setDescription(String description);

	/**
	 * Returns the quantity of this temp cargo items.
	 *
	 * @return the quantity of this temp cargo items
	 */
	public double getQuantity();

	/**
	 * Sets the quantity of this temp cargo items.
	 *
	 * @param quantity the quantity of this temp cargo items
	 */
	public void setQuantity(double quantity);

	/**
	 * Returns the unit of this temp cargo items.
	 *
	 * @return the unit of this temp cargo items
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this temp cargo items.
	 *
	 * @param unit the unit of this temp cargo items
	 */
	public void setUnit(String unit);

	/**
	 * Returns the sequence of this temp cargo items.
	 *
	 * @return the sequence of this temp cargo items
	 */
	public int getSequence();

	/**
	 * Sets the sequence of this temp cargo items.
	 *
	 * @param sequence the sequence of this temp cargo items
	 */
	public void setSequence(int sequence);

	/**
	 * Returns the modified date of this temp cargo items.
	 *
	 * @return the modified date of this temp cargo items
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this temp cargo items.
	 *
	 * @param modifiedDate the modified date of this temp cargo items
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempCargoItems tempCargoItems);

	public int hashCode();

	public CacheModel<TempCargoItems> toCacheModel();

	public TempCargoItems toEscapedModel();

	public String toString();

	public String toXmlString();
}