/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import vn.gt.dao.noticeandmessage.service.persistence.IssueShiftingOrderChanelPK;

import java.io.Serializable;

/**
 * The base model interface for the IssueShiftingOrderChanel service. Represents a row in the &quot;ISSUE_SHIFTING_ORDER_CHANEL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.IssueShiftingOrderChanelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.IssueShiftingOrderChanelImpl}.
 * </p>
 *
 * @author win_64
 * @see IssueShiftingOrderChanel
 * @see vn.gt.dao.noticeandmessage.model.impl.IssueShiftingOrderChanelImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.IssueShiftingOrderChanelModelImpl
 * @generated
 */
public interface IssueShiftingOrderChanelModel extends BaseModel<IssueShiftingOrderChanel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a issue shifting order chanel model instance should use the {@link IssueShiftingOrderChanel} interface instead.
	 */

	/**
	 * Returns the primary key of this issue shifting order chanel.
	 *
	 * @return the primary key of this issue shifting order chanel
	 */
	public IssueShiftingOrderChanelPK getPrimaryKey();

	/**
	 * Sets the primary key of this issue shifting order chanel.
	 *
	 * @param primaryKey the primary key of this issue shifting order chanel
	 */
	public void setPrimaryKey(IssueShiftingOrderChanelPK primaryKey);

	/**
	 * Returns the shifting order ID of this issue shifting order chanel.
	 *
	 * @return the shifting order ID of this issue shifting order chanel
	 */
	public long getShiftingOrderId();

	/**
	 * Sets the shifting order ID of this issue shifting order chanel.
	 *
	 * @param shiftingOrderId the shifting order ID of this issue shifting order chanel
	 */
	public void setShiftingOrderId(long shiftingOrderId);

	/**
	 * Returns the chanel code of this issue shifting order chanel.
	 *
	 * @return the chanel code of this issue shifting order chanel
	 */
	@AutoEscape
	public String getChanelCode();

	/**
	 * Sets the chanel code of this issue shifting order chanel.
	 *
	 * @param chanelCode the chanel code of this issue shifting order chanel
	 */
	public void setChanelCode(String chanelCode);

	/**
	 * Returns the chanel name of this issue shifting order chanel.
	 *
	 * @return the chanel name of this issue shifting order chanel
	 */
	@AutoEscape
	public String getChanelName();

	/**
	 * Sets the chanel name of this issue shifting order chanel.
	 *
	 * @param chanelName the chanel name of this issue shifting order chanel
	 */
	public void setChanelName(String chanelName);

	/**
	 * Returns the order of this issue shifting order chanel.
	 *
	 * @return the order of this issue shifting order chanel
	 */
	public int getOrder();

	/**
	 * Sets the order of this issue shifting order chanel.
	 *
	 * @param order the order of this issue shifting order chanel
	 */
	public void setOrder(int order);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(IssueShiftingOrderChanel issueShiftingOrderChanel);

	public int hashCode();

	public CacheModel<IssueShiftingOrderChanel> toCacheModel();

	public IssueShiftingOrderChanel toEscapedModel();

	public String toString();

	public String toXmlString();
}