/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserSign service. Represents a row in the &quot;user_sign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.common.model.impl.UserSignModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.common.model.impl.UserSignImpl}.
 * </p>
 *
 * @author win_64
 * @see UserSign
 * @see vn.gt.dao.common.model.impl.UserSignImpl
 * @see vn.gt.dao.common.model.impl.UserSignModelImpl
 * @generated
 */
public interface UserSignModel extends BaseModel<UserSign> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user sign model instance should use the {@link UserSign} interface instead.
	 */

	/**
	 * Returns the primary key of this user sign.
	 *
	 * @return the primary key of this user sign
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user sign.
	 *
	 * @param primaryKey the primary key of this user sign
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this user sign.
	 *
	 * @return the ID of this user sign
	 */
	public long getId();

	/**
	 * Sets the ID of this user sign.
	 *
	 * @param id the ID of this user sign
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this user sign.
	 *
	 * @return the user ID of this user sign
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user sign.
	 *
	 * @param userId the user ID of this user sign
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user sign.
	 *
	 * @return the user uuid of this user sign
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user sign.
	 *
	 * @param userUuid the user uuid of this user sign
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the port code of this user sign.
	 *
	 * @return the port code of this user sign
	 */
	@AutoEscape
	public String getPortCode();

	/**
	 * Sets the port code of this user sign.
	 *
	 * @param portCode the port code of this user sign
	 */
	public void setPortCode(String portCode);

	/**
	 * Returns the title of this user sign.
	 *
	 * @return the title of this user sign
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this user sign.
	 *
	 * @param title the title of this user sign
	 */
	public void setTitle(String title);

	/**
	 * Returns the representative of this user sign.
	 *
	 * @return the representative of this user sign
	 */
	@AutoEscape
	public String getRepresentative();

	/**
	 * Sets the representative of this user sign.
	 *
	 * @param representative the representative of this user sign
	 */
	public void setRepresentative(String representative);

	/**
	 * Returns the file chu ky ID of this user sign.
	 *
	 * @return the file chu ky ID of this user sign
	 */
	public long getFileChuKyId();

	/**
	 * Sets the file chu ky ID of this user sign.
	 *
	 * @param fileChuKyId the file chu ky ID of this user sign
	 */
	public void setFileChuKyId(long fileChuKyId);

	/**
	 * Returns the file con dau ID of this user sign.
	 *
	 * @return the file con dau ID of this user sign
	 */
	public long getFileConDauId();

	/**
	 * Sets the file con dau ID of this user sign.
	 *
	 * @param fileConDauId the file con dau ID of this user sign
	 */
	public void setFileConDauId(long fileConDauId);

	/**
	 * Returns the file chung thu so ID of this user sign.
	 *
	 * @return the file chung thu so ID of this user sign
	 */
	public long getFileChungThuSoId();

	/**
	 * Sets the file chung thu so ID of this user sign.
	 *
	 * @param fileChungThuSoId the file chung thu so ID of this user sign
	 */
	public void setFileChungThuSoId(long fileChungThuSoId);

	/**
	 * Returns the modify user of this user sign.
	 *
	 * @return the modify user of this user sign
	 */
	@AutoEscape
	public String getModifyUser();

	/**
	 * Sets the modify user of this user sign.
	 *
	 * @param modifyUser the modify user of this user sign
	 */
	public void setModifyUser(String modifyUser);

	/**
	 * Returns the modify date of this user sign.
	 *
	 * @return the modify date of this user sign
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this user sign.
	 *
	 * @param modifyDate the modify date of this user sign
	 */
	public void setModifyDate(Date modifyDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(UserSign userSign);

	public int hashCode();

	public CacheModel<UserSign> toCacheModel();

	public UserSign toEscapedModel();

	public String toString();

	public String toXmlString();
}