/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.common.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.gt.dao.common.model.UserSign;
import vn.gt.dao.common.service.UserSignLocalServiceUtil;

/**
 * The extended model base implementation for the UserSign service. Represents a row in the &quot;user_sign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserSignImpl}.
 * </p>
 *
 * @author win_64
 * @see UserSignImpl
 * @see vn.gt.dao.common.model.UserSign
 * @generated
 */
public abstract class UserSignBaseImpl extends UserSignModelImpl
	implements UserSign {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user sign model instance should use the {@link UserSign} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			UserSignLocalServiceUtil.addUserSign(this);
		}
		else {
			UserSignLocalServiceUtil.updateUserSign(this);
		}
	}
}