/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.gt.dao.noticeandmessage.model.TempMaritimePaymentConfig;
import vn.gt.dao.noticeandmessage.service.TempMaritimePaymentConfigLocalServiceUtil;

/**
 * The extended model base implementation for the TempMaritimePaymentConfig service. Represents a row in the &quot;TEMP_MARITIME_PAYMENT_CONFIG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TempMaritimePaymentConfigImpl}.
 * </p>
 *
 * @author win_64
 * @see TempMaritimePaymentConfigImpl
 * @see vn.gt.dao.noticeandmessage.model.TempMaritimePaymentConfig
 * @generated
 */
public abstract class TempMaritimePaymentConfigBaseImpl
	extends TempMaritimePaymentConfigModelImpl
	implements TempMaritimePaymentConfig {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a temp maritime payment config model instance should use the {@link TempMaritimePaymentConfig} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			TempMaritimePaymentConfigLocalServiceUtil.addTempMaritimePaymentConfig(this);
		}
		else {
			TempMaritimePaymentConfigLocalServiceUtil.updateTempMaritimePaymentConfig(this);
		}
	}
}